#!/usr/bin/env bash
set -x
BINDIR=$(dirname "$0")
BINARY=$1
INPUT_TRAIN=$2
INPUT_TEST=$3
OUT=$4
TREEMARGIN=$5
DISTWT=$6
ALLFLAG=$7
ITER=$8
MARGINTHRES=$9
CNT=${10}
REALFEAT_CNT=${11}
MINNEIGH=${12}
MINWT=${13}
MAXNEIGH=${14}
MAXWT=${15}
NEIGHSTEP=${16}
WTSTEP=${17}
DISTSCALE=${18}
RANDOMCNT=${19}
TOPFIXED=${20}
FEAT_CNT=${21}


check_errs() 
{ 
  # Function. 
  if [ "${1}" != "0" ]; then 
    exit ${2} 
  fi 
} 

TREE_MODEL=${OUT}_Tree.model
KNN_MODEL=${OUT}_KNN.model
RATIOF=${OUT}.ratio
$BINDIR/Sentieon_BioM_Train.sh $BINARY $INPUT_TRAIN $TREE_MODEL $KNN_MODEL $TREEMARGIN $DISTWT $ALLFLAG $ITER $RATIOF
$BINDIR/Sentieon_BioM_Test.sh $BINARY $INPUT_TRAIN $INPUT_TEST $OUT $TREE_MODEL $KNN_MODEL $MARGINTHRES $CNT $ALLFLAG $REALFEAT_CNT $MINNEIGH $MINWT $MAXNEIGH $MAXWT $NEIGHSTEP $WTSTEP $DISTSCALE $RANDOMCNT $TOPFIXED $FEAT_CNT

