#!/usr/bin/env bash
set -x
BINDIR=$(dirname "$0")
BINARY=$1
INPUT_TRAIN=$2
INPUT_TEST=$3
OUTPUT=$4
TREE_MODEL=$5
KNN_MODEL=$6
MARGINTHRES=$7
CNT=$8
ALLFLAG=$9
REALFEAT_CNT=${10}
MINNEIGH=${11}
MINWT=${12}
MAXNEIGH=${13}
MAXWT=${14}
NEIGHSTEP=${15}
WTSTEP=${16}
DISTSCALE=${17}
RANDOMCNT=${18}
TOPFIXED=${19}
FEAT_CNT=${20}

TREERESULTS=${OUTPUT}_tree.result
$BINARY 1 $TREE_MODEL ${INPUT_TEST}_Phenotype.tsv ${INPUT_TEST}_FeatureMatrix.tsv > $TREERESULTS

KNNRESULTS=${OUTPUT}_KNN.result
$BINARY 3 ${INPUT_TRAIN}_Outcome.tsv ${INPUT_TRAIN}_Phenotype.tsv ${INPUT_TRAIN}_FeatureMatrix.tsv $KNN_MODEL ${INPUT_TEST}_Phenotype.tsv ${INPUT_TEST}_FeatureMatrix.tsv $ALLFLAG $REALFEAT_CNT $MINNEIGH $MINWT $MAXNEIGH $MAXWT $NEIGHSTEP $WTSTEP $DISTSCALE $RANDOMCNT $TOPFIXED $FEAT_CNT > $KNNRESULTS

FINALPROB=${OUTPUT}_Final.prob
$BINARY 4 $TREERESULTS $KNNRESULTS $MARGINTHRES > $FINALPROB

FINALRESULT=${OUTPUT}_Final.result
$BINARY 6 $FINALPROB $CNT > $FINALRESULT

