#!/usr/bin/env bash
set -x
BINDIR=$(dirname "$0")
BINARY=$1
INPUT_TRAIN=$2
INPUT_TEST=$3
OUT=$4
LOG=$5
TREEMARGIN=$6
DISTWT=$7
ALLFLAG=$8
ITER=$9
MARGINTHRES=${10}
CNT=${11}
REALFEAT_CNT=${12}
MINNEIGH=${13}
MINWT=${14}
MAXNEIGH=${15}
MAXWT=${16}
NEIGHSTEP=${17}
WTSTEP=${18}
DISTSCALE=${19}
RANDOMCNT=${20}
TOPFIXED=${21}
FEAT_CNT=${22}

$BINDIR/Sentieon_BioM_TrainTest.sh $BINARY $INPUT_TRAIN $INPUT_TEST $OUT $TREEMARGIN $DISTWT $ALLFLAG $ITER $MARGINTHRES $CNT $REALFEAT_CNT $MINNEIGH $MINWT $MAXNEIGH $MAXWT $NEIGHSTEP $WTSTEP $DISTSCALE $RANDOMCNT $TOPFIXED $FEAT_CNT

$BINARY 5 ${INPUT_TEST}_Outcome.tsv ${OUT}_Final.prob $CNT >> $LOG
